language: java
jdk: openjdk11 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  slack: miw-upm:14r71Q31vHeCLpklYhZhbsu1
  email:
    recipients:
      - mohammed.bendohhou.laouini@alumnos.upm.es
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=mbendohhoulaouini -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    branch: master
  app: iwvg-devops-mohammed-bendohhou