language: java
jdk: openjdk11 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - mohammed.bendohhou.laouini@alumnos.upm.es
